project            = "play-with-terraform"
environment        = "production"
environment_short  = "prd"
region             = "us-west-2"
cidr_block         = "10.1.0.0/16"
availability_zones = "us-west-2a,us-west-2b,us-west-2c"
