name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Terraform Init
        run: terraform init

      - name: Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Lint
        run: |
          tflint --init
          tflint --recursive
